### ISSUE TITLE
Keymaps (and alternative)

### ISSUE THREAD

**Issue by reagle** [m-bartlett/SublimeFontSizePerView#1]
Thanks for this! I installed from package control but can't access keymap: "The settings file "res://Packages/
FontSizePerView/Default.sublime-keymap" could not be opened OK".

BTW: Did you see the code in [#1551](https://github.com/sublimehq/sublime_text/issues/1551) thread?

![SCR-20221212-lqw](https://user-images.githubusercontent.com/596814/207150158-a8f9823e-b082-42d6-af49-ddf297e7b026.png)

**Comment by m-bartlett** [comment]
@reagle Thanks for sharing, it took me a while to have access to a Mac to test. That error seems to be a result of a filesystem path inconsistency that was introduced by this plugin getting renamed to have spaces once it was merged into the Package Control channel (i.e. it was originaly `FontSizePerView` but is now `Font Size Per View`.

#2 resolves this in my testing (note that I had to quit and restart Sublime Text when installing it manually from `git clone` to resolve `ImportError`s it was throwing in the console).

Are you able to test using the [macos-fix branch](https://github.com/m-bartlett/SublimeFontSizePerView/tree/macos-fix) and let me know if it works for you now? I added [MacOS-specific instructions for manually installing](https://github.com/m-bartlett/SublimeFontSizePerView/tree/macos-fix#macos) in that branch's README.

Also for convenience, I added a command palette command to open the keybinding settings (`Font Size Per View: Open Key Binding Settings`) in addition to the menubar entry.

**Edit**: I actually was not aware of https://github.com/sublimehq/sublime_text/issues/1551, I just inspected the `View` object from the sublime console and noticed some font settings in the API docs and eventually noticed this plugin was possible.

**Comment by reagle** [comment]
Yes, that seems to work, but I prefer the [syntax-wide settings](https://github.com/sublimehq/sublime_text/issues/1551#issuecomment-1348150261) from @deathaxe , so I'm going to keep using that.
